// Created by Divya for Constants
public class B2B_Constants {
    public static final STRING DIRECTSHIP = 'DirectShip';
    public static final STRING ACTIVATED = 'Activated';
    public static final STRING PARTIAL_SHIP = 'Partially Shipped';
    public static final STRING INPROGRESS = 'In Progress';
    public static final STRING PREPARING_FOR_SHIPMENT = 'Preparing for Shipment';
    public static final STRING PROCESSING_IN_WAREHOUSE = 'Processing In Warehouse';
    public static final STRING PAYMENT_ISSUE = 'Payment Issue';
    public static final STRING ORDER_ISSUE = 'Order Issue';
}