public class NotificationRequest {
    
    
    public boolean Subscribe{get;set;}
    public boolean Resubscribe{get;set;}
    public list<string> mobileNumbers{get;set;}
    //public String mobileNumbers{get;set;}
    public String keyword{get;set;}    //TESTLYAPI
    public boolean Override2{get;set;}
    public String messageText{get;set;}    //Opportunity - <Opportunity Name> has been assigned
    
    
    
}